cv_review_task:
  description: >
    Review the following CV and identify areas for improvement. Be as specific as possible. And reference parts of the CV as evidence.
    {cv_text}
  expected_output: >
    A list of bullet points detailing specific ways the CV can be improved.
  agent: cv_reviewer

cover_letter_task:
  description: >
    Read the provided CV
    {cv_text}
    and review the following job description: {job_description}.
    Write a tailored cover letter that demonstrates how the applicant's experience matches the job requirements.
  expected_output: >
    A cover letter formatted as markdown (without '```') that highlights how the applicant meets the job requirements using information from the CV.
  agent: cover_letter_writer